FROM opensuse

VOLUME /output

ENV OUTPUT_DIR /build/dist
ENV BUILD_DIR /build

RUN zypper in -y \
   rpm-build \
   make \
   bash \
  && zypper clean -a

WORKDIR $BUILD_DIR
COPY . .

CMD ["./pkg/dockerfiles/rpm-entrypoint.sh"]
